version: '2'
services:
  zira-client:
    restart: always
    image: zira-client
    container_name: zira-client
    ports:
      - '80'
    networks:
      - zira
networks:
  zira:
    external: true
