version: '2'
services:
  zira-client:
    restart: always
    image: zira-client
    container_name: zira-client
    ports:
      - '8081:80'
    networks:
      - front
networks:
  front:
    external:
      name: zira-proxy_front
